### ISSUE TITLE
Avatar 初始样式错误

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-miniprogram#107]
**对应的组件**

Avatar

**相关环境**

基础库版本：最新

运行环境：开发者工具

**出现的问题**

按官网的示例使用:

```
<t-avatar icon="user" t-class-icon="default-user" />
```

是没有任何样式的。需要手动实现 `default-user` 相关的样式：

```css
.default-user {
    background-color: #e7e7e7;
    color: #c5c5c5;
    font-size: 60rpx;
  }
```

**我的预期**

应该是有默认的样式，而不是通过 externClass 来实现这默认样式

**附加信息**

相关链接：https://txc.qq.com/products/293854/post/164195607783926055/
