### ISSUE TITLE
[NavBar] 在自定义组件中使用 NavBar 时，全局样式配置的样式不起作用

### ISSUE THREAD

**Issue by YanmaY** [Tencent/tdesign-miniprogram#1306]
### tdesign-miniprogram 版本

0.32.0

### 重现步骤

``` html
<!--components/Unlogin/Unlogin.wxml-->
<t-navbar title="标题" t-class-title="nav-title" />
```
``` css
// app.scss
.nav-title {
    color: #fff;
    font-weight: bold;
    letter-spacing: 1rpx;
    font-size: 32rpx !important;
}
```

### 期望结果

在自定义组件中使用 NavBar 时，全局样式配置的样式正常生效

### 实际结果

在自定义组件中使用 NavBar 时，全局样式配置的样式未正常生效，普通页面使用 NavBar 时全局样式可以正常生效

### 框架版本

原生小程序

### 浏览器版本

Edge

### 系统版本

Win11`

### Node版本

14.20.0
