### ISSUE TITLE
[Navbar导航栏] 自定义颜色功能无效

### ISSUE THREAD

**Issue by 513205785Xie** [Tencent/tdesign-miniprogram#1570]
### tdesign-miniprogram 版本

1.0.0-rc

### 重现步骤

按照[文档](https://tdesign.tencent.com/miniprogram/components/navbar?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)使用navbar组件自定义样式功能
custom-navbar.wxml
``` wxml
<t-navbar class="custom-navbar" title="自定义标题"></t-navbar>
```
custom-navbar.json
``` json
{
    "component": true,
    "usingComponents": {
        "t-navbar": "tdesign-miniprogram/navbar/navbar",
        "t-icon": "tdesign-miniprogram/icon/icon"
    }
}
```
custom-navbar.less
``` less
.custom-navbar {
    --td-navbar-color: #fff;
    --td-navbar-bg-color: #0052d9;
    --td-navbar-title-font-size: 24rpx;
}
```
自定义的样式没有生效
<img width="322" alt="image" src="https://user-images.githubusercontent.com/22184621/217775576-2345ff8a-d5dc-4136-8b5d-1790dcdb3cee.png">

### 期望结果

样式生效

### 实际结果

样式未生效

### 基础库版本

2.30.0
