### ISSUE TITLE
使用sass自定义样式无效

### ISSUE THREAD

**Issue by jiayafei** [Tencent/tdesign-miniprogram#1749]
### tdesign-miniprogram 版本

1.0.1

### 重现步骤

在app.scss中写入下面内容
$primary-color: var(--td-primary-color, #00ff00); // 主题色
$success-color: var(--td-success-color, #00ff00); // 成功
$warning-color: var(--td-warning-color, #00ff00); // 警告
$error-color: var(--td-error-color, #00ff00); // 失败
页面中使用组件，样式颜色无法更改

### 期望结果

更改

### 实际结果

目前不会自定义样式

### 补充说明

1.0.1

**Comment by LeeJim** [comment]
你这样的写法是定义 sass 变量，并没有修改到 CSS Varaibles 的变量。
你可以这样写:
```scss
$primary-color: #00ff00;

page {
  --td-primary-color: $primary-color;
}
```
