### ISSUE TITLE
配置主题色

### ISSUE THREAD

**Issue by lolhezihehe** [Tencent/tdesign-miniprogram#1782]
### tdesign-miniprogram 版本

1.0.3

### 重现步骤

使用 TDdesign-组件库模板
配置 app.wxss 
```css
page {
  background: #f6f6f6;
  --td-primary-color: green; 
  --td-primary-color-7: green;
}
```

### 期望结果

`--td-primary-color` 生效

### 实际结果

只有 `--td-primary-color-7` 生效，`--td-primary-color` 不生效，其他颜色比如 --td-primary-color-8 还是蓝色

### 基础库版本

2.30.2

### 补充说明

看了下  **_variables.less**  文件没有 `--td-primary-color` 变量，配置主题色只能修改 `--td-primary-color-1` 到 `--td-primary-color-9`
