### ISSUE TITLE
[t-button] 'suffix' 属性不起作用

### ISSUE THREAD

**Issue by zsying** [Tencent/tdesign-miniprogram#1784]
### tdesign-miniprogram 版本

1.0.3

### 重现步骤

在t-button组件中，设定 content 和suffix
`
<t-button disabled="{{finished}}" bindtap="clickNext" content="下一页">
      <t-icon name="chevron-right" slot="suffix"></t-icon>
</t-button>
`

### 期望结果

显示 ：   下一页 >    

### 实际结果

下一页
 > 

### 补充说明

代码中未实现   suffix

**Comment by yaogengzhu** [comment]
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/42566669/225826375-da34f351-698e-4a21-8c9b-43ce56174bc2.png">

不同层级也能包裹住？啥情况勒


解决这个

```less
  &__content {
    display: flex;
    align-items: center;
  }
```
