### ISSUE TITLE
如何修改选中的item的背景色?

### ISSUE THREAD

**Issue by YangRucheng** [Tencent/tdesign-miniprogram#1999]
### 这个功能解决了什么问题

![image](https://github.com/Tencent/tdesign-miniprogram/assets/60175467/54578e77-4694-475f-b637-cec3cea239cb)
```css
page{
    --td-tab-bar-active-color: #FF0C0C !important;
    --td-tab-bar-bg-color: #FFDEDE !important;
    --td-tab-bar-border-color: #1cc29e !important;
    --td-tab-bar-hover-color: rgb(216, 213, 25) !important;
    --td-tab-bar-item-color: rgb(218, 182, 21) !important;
    --td-tab-bar-item-active-color: rgb(212, 31, 197) !important;
}
```
我想修改"首页"的背景色, 应该怎么做? 默认是TDdesgin的淡蓝色

### 你建议的方案是什么

css变量控制背景色
