### ISSUE TITLE
[Fab] 自定义主题色时，Fab点击态颜色没发生变化

### ISSUE THREAD

**Issue by ElanYoung** [Tencent/tdesign-miniprogram#2075]
### tdesign-miniprogram 版本

1.1.8

### 重现步骤

```html
<t-fab icon="add"></t-fab>
```

```css
page {
  /* 自定义主题色 */
  --td-brand-color: #ff2442;
}
```

### 期望结果

希望自定义主题色时，点击fab时，点击态颜色发生变化

### 实际结果

自定义主题色时，点击fab时，点击态颜色还是TDesign主题色

### 基础库版本

2.32.1
