### ISSUE TITLE
[Navbar&Indexes] 将Navbar的变量改为全局变量以及联用Indexes时锚点吸附问题

### ISSUE THREAD

**Issue by Junzzzz** [Tencent/tdesign-miniprogram#2304]
### 关于 `Navbar` 变量设置：

感觉经常会用到 `--td-navbar-height` 这个变量来指定容器的高度，但是这个变量被限制在了 `Navbar` 元素之内，其他组件需要获取时只能重新计算一遍，比较麻烦（不过最后都用其他办法绕过去了，但是如果有这个变量会方便很多）

---

### 关于 `Indexes` 和 `Navbar` 联用锚点吸附问题：

虽然有 `stickyOffset` 这个变量，但是得在页面加载时计算这个值有点麻烦

### 你建议的方案是什么

我看[微信文档](https://developers.weixin.qq.com/miniprogram/dev/component/page-meta.html)里似乎可以给Page设置样式

加一段：`<page-meta page-style="{{ styles }}"/>` 就行了

不过版本似乎需要 `2.9.0`，不知道还有没有其他办法

---

如果上面那个全局变量实现了，可以给锚点的top加个变量

```less
&--sticky {
  position: fixed;
  top: var(--td-indexes-anchor-top, 0);
  left: 0;
  width: 100%;
  z-index: 1;
}
```

然后直接设置这个变量值为 `var(--td-navbar-height)` 就行了

---

另外我发现下面代码里 `wx.getSystemInfo` 和 `wx.getSystemInfoSync` 是不是重复了

https://github.com/Tencent/tdesign-miniprogram/blob/cdce071c9639c68a56c0ba5c3d2037c22116185c/src/navbar/navbar.ts#L73-L92
