### ISSUE TITLE
swipe-cell 真机下无法使用，操作无反馈；开发者工具可以正常预览、操作反馈。

### ISSUE THREAD

**Issue by makecoder** [Tencent/tdesign-miniprogram#2500]
### swipe-cell 无法使用
在开发者工具里预览正常，左滑有反馈，但是在真机上预览、真机调试、体验版左滑都无反馈。
开发者工具信息如下：
[system] WeChatLib: 3.0.1 (2023.8.30 19:21:49)
[system] Subpackages: N/A
[system] LazyCodeLoading: true

开发调试所用的手机设备如下：
华为 P30 pro（鸿蒙3.0.0）：微信版本8.0.43
iPhone13（iOS15.5）：微信版本8.0.44

### 代码如下
huadong.json
``` json
{
  "usingComponents": {
    "t-swipe-cell": "tdesign-miniprogram/swipe-cell/swipe-cell",
    "t-cell": "tdesign-miniprogram/cell/cell"
  }
}
```
huadong.js
``` javascript
//开发者默认生成的代码，无改动
```
huadong.wxml
``` html
<!--pages/huadong/huadong.wxml-->
<view style="margin-top: 300rpx;background-color: aquamarine;">pages/huadong/huadong.wxml</view>
<t-swipe-cell opened="{{true}}">
  <t-cell title="左滑多操作" note="辅助信息" bordered="{{true}}" />
  <view slot="right" class="btn-wrapper">
    <view class="btn favor-btn" bind:tap="onFavor">收藏</view>
    <view class="btn edit-btn" bind:tap="onEdit">编辑</view>
    <view class="btn delete-btn" bind:tap="onDelete">删除</view>
  </view>
</t-swipe-cell>
```

huadong.wxss
``` css
/* pages/huadong/huadong.wxss */

.btn-wrapper {
  height: 100%;
}

.btn {
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 120rpx;
  height: 100%;
  color: white;
}

.delete-btn {
  background-color: #e34d59;
}

.copy-btn {
  background-color: var(--td-brand-color);
}

.favor-btn {
  background-color: #0052d9;
}

.column {
  flex-direction: column;
}

.padding-bottom {
  padding-bottom: 8rpx;
}
```
