### ISSUE TITLE
[深色模式][Avatar] TD 官方小程序深色模式 Avatar 页面 Primary 配色错误 [Navbar] 深色模式大标题颜色出错

### ISSUE THREAD

**Issue by ArcticFoxPro** [Tencent/tdesign-miniprogram#2721]
### tdesign-miniprogram 版本

1.3.0

### 重现链接

微信搜一搜“TDesign组件库”（即你们自家的示例小程序会复现此问题）

### 重现步骤

深色模式下进入 TDesign组件库 微信小程序后：

1. 点击“数据展示”-“ Avatar 头像”

### 期望结果

界面所有 Primary 色均为深色模式 Primary 色 #4582E6

### 实际结果

出现浅色模式 Primary 色 #0052d9

![Screenshot_2024-04-23-14-33-45-228_com.tencent.mm-edit.jpg](https://github.com/Tencent/tdesign-miniprogram/assets/139336664/26ac1048-c96c-4a6c-b0b3-b40bac006071)

### 基础库版本

未知。如有需要，需要 TDesign组件库 示例小程序开发者自行查看其基础库。

### 补充说明

@anlyyao 让我填的。

### tdesign-miniprogram 版本

1.3.0

### 重现链接

微信搜一搜“TDesign组件库”（即你们自家的示例小程序会复现此问题）

### 重现步骤

深色模式下进入 TDesign组件库 微信小程序后：

1. 点击“导航”-“ Navbar”

### 期望结果

大标题不出现颜色异常，navbar 与自定义组件背景色一致，符合设计稿

### 实际结果

大标题出现颜色异常，navbar 与自定义组件背景色不一致，不符合设计稿

![mmexport1713859015910.jpg](https://github.com/Tencent/tdesign-miniprogram/assets/139336664/ae79fd82-ca60-4434-a3ca-a70a3453f646)

疑似起源问题是文档代码出错：

https://tdesign.tencent.com/miniprogram/components/navbar#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F

```css
.header-title {
  font-size: 28px;
  line-height: 36px;
  padding: 8rpx 32rpx 16rpx;
  background-color: var(--bg-color-demo);
  font-weight: 600;
  color: var(--td-text-color-primary);
}
```

`background-color: var(--bg-color-demo);` 设置出错，应该跟随 navbar 背景色。

### 基础库版本

未知。如有需要，需要 TDesign组件库 示例小程序开发者自行查看其基础库。

### 补充说明

无
