### ISSUE TITLE
[t-avatar-group] props设置为10以上会不显示

### ISSUE THREAD

**Issue by FlyingDreamSky** [Tencent/tdesign-miniprogram#3088]
### tdesign-miniprogram 版本

1.5.1

### 重现步骤

          <t-avatar-group max="20" t-class="flex-wrap" collapseAvatar="more">
            <t-avatar wx:for="{{avatarList}}" wx:for-item="pic" wx:key="index" image="{{pic}}" />
          </t-avatar-group>

### 期望结果

超过10以上的，zindex能正常计算

### 实际结果

超过10之后，zindex为负数

**Comment by betavs** [comment]
```css
/* 在 wxss 文件中定义 flex-wrap */

.flex-wrap {
  flex-wrap: wrap;
}

```
