### ISSUE TITLE
[t-button] variant设置为outline的问题

### ISSUE THREAD

**Issue by wanhuihan** [Tencent/tdesign-miniprogram#3514]
### tdesign-miniprogram 版本

1.8.0

### 重现步骤

 <t-button theme="danger" variant="outline" block icon="close-circle">关闭比赛</t-button> 这个的效果和<t-button size="large" theme="danger" variant="text">文字按钮</t-button>的效果是一样的，

### 期望结果

期望variant为outline的时候是线性边框，只有在variant为text的时候是文字按钮

**Comment by Boomkaa** [comment]
@wanhuihan 根据您现在提供给的信息无法复现此的问题。贴个完整代码看看吧～

**Comment by anlyyao** [comment]
@wanhuihan 难道现在不是嘛？ 官网示例是符合预期的哈，你拉官网示例代码看看吧，效果如下图：
<img width="1611" alt="Image" src="https://github.com/user-attachments/assets/0491b1e8-1788-470d-b990-5d78bd2ec897" />

**Comment by CrazyOrr** [comment]
- tdesign-miniprogram 版本: 1.9.1
- 调试基础库版本: 3.8.3
- 微信开发者工具版本: 1.06.2412050
- 渲染模式: webview

`<t-button variant="outline">按钮</t-button>` 无边框，与 `<t-button variant="text">按钮</t-button>` 样式相同，并且带有以下样式：
```css
wx-button:not([size=mini]) {
    margin-left: auto;
    margin-right: auto;
    width: 184px;
}
```
